### ISSUE TITLE
Tyxml_js depends on reactiveData

### ISSUE THREAD

**Issue by xvw** [ocsigen/old.ocsigen.org#22]
When I visit the https://ocsigen.org/js_of_ocaml/ page, I think understand that Tyxml_js depends reactiveData is quite complex.
Perhaps ReactiveData should be documented on the page (instead of github.io) and ReactiveData an js_of_ocaml.tyxml dependency.

Thank you for your work!

**Comment by vasilisp** [comment]
Acknowledged. Describing optional dependencies is quite hard (we almost have to resort to logical constraints), but we should try.
