### ISSUE TITLE
New infrastructure

### ISSUE THREAD

**Issue by vasilisp** [ocsigen/old.ocsigen.org#32]
The current site infrastructure is hard to maintain. It would be nice to migrate to mostly static content.

I think our discussions converge on a modern Bootstrap-style homepage that points to the relevant places. We can take [ocaml.org](https://ocaml.org/) as an inspiration. I personally think that we should just point `ocsigen.org` to what is now `ocsigen.github.io`, and use GitHub Pages (basically Jekyll) for almost everything. If we decide to do so, it will be trivial to integrate the [blog posts](https://ocsigen.github.io) and hence ensure that `ocsigen.org` feels active.

The big obstacle is the current manual/tutorial/API documentation that use `wikidoc` syntax. In principle, we could implement static infrastructure for these that retains the existing functionality (e.g., trans-project links). But that would involve maintaining a new tool with questionable usefulness outside Ocsigen. In the spirit of simplifying our workflow, I would personally prefer just using Ocamldoc/odoc functionality for the API doc (with manual strategically-placed links where needed), and an one-off translation of the manuals and the more important tutorials to a simpler format (e.g., `markdown`). Given static docs, we can either put them in GitHub pages or in dedicated docs infrastructure like [Read the Docs](https://readthedocs.org/).

**Comment by vasilisp** [comment]
In the process, we should also address #30 :).

**Comment by Drup** [comment]
Odoc will be able to use `.mld` files in ocamldoc syntax that are linked together and create manual pages. I think this would be a very good solutions for the manual. See https://github.com/ocaml-doc/odoc/issues/61
